  {{- $name := include "coupon-api.fullname" . -}}
  {{- $nosqlsrv := include "mongo-name" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "cfg-{{ $name }}"
  labels:
    app: {{ template "coupon-api.name" . }}
    chart: {{ template "coupon-api.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  coupon__ConnectionString: mongodb://{{ $nosqlsrv }}
  urls__IdentityUrl: http://{{ .Values.app.svc.identity }}
  all__EventBusConnection: {{ .Values.inf.eventbus.constr }}
  all__InstrumentationKey: "{{ .Values.inf.appinsights.key }}"
  all__UseAzureServiceBus: "{{ .Values.inf.eventbus.useAzure }}"